# Generated by Django 4.2.7 on 2025-07-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='free_addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_in_promotions', to='api.addon', verbose_name='Бесплатное дополнение'),
        ),
    ]
