# Generated by Django 4.2.7 on 2025-07-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_promotion_free_addon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='addon',
            name='available_for_categories',
            field=models.ManyToManyField(blank=True, related_name='available_addons', to='api.category', verbose_name='Доступно для категорий'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная сумма для бесплатной доставки'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Комментарии клиента', verbose_name='Примечания к заказу'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная сумма скидки'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество использований'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество использований'),
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='description',
            field=models.TextField(blank=True, help_text='Например: 30 см, 8 кусочков', verbose_name='Описание размера'),
        ),
        migrations.AddIndex(
            model_name='addon',
            index=models.Index(fields=['category', 'is_active'], name='api_addon_categor_c2189f_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['priority'], name='api_menuite_priorit_8d768b_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_hit', 'priority', 'created_at'], name='api_menuite_is_hit_60d4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_new', 'priority', 'created_at'], name='api_menuite_is_new_07042b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_time'], name='api_order_deliver_8f8f17_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='api_order_user_id_536555_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='api_order_status_1d49fe_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['usage_count'], name='api_promoti_usage_c_98039b_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['max_uses'], name='api_promoti_max_use_40ea11_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_to'], name='api_promoti_is_acti_c476a6_idx'),
        ),
    ]
