# Generated by Django 4.2.7 on 2025-08-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menuitem_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.user')),
            ],
            options={
                'verbose_name': 'Избранный товар',
                'verbose_name_plural': 'Избранные товары',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='api_favorit_user_id_b3c1a4_idx'), models.Index(fields=['menu_item'], name='api_favorit_menu_it_611c51_idx'), models.Index(fields=['user', 'created_at'], name='api_favorit_user_id_e83d1c_idx')],
                'unique_together': {('user', 'menu_item')},
            },
        ),
    ]
