# Generated by Django 4.2.7 on 2025-08-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, help_text='Массив координат [[широта, долгота], ...] для точных границ зоны', null=True, verbose_name='Координаты полигона'),
        ),
    ]
