# Generated by Django 4.2.7 on 2025-08-24 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_deliveryzone_polygon_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='polygon_fill_color',
            field=models.CharField(default='#ffd21e', help_text='Цвет в формате #RRGGBB (например: #ffd21e)', max_length=7, verbose_name='Цвет заливки полигона'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='polygon_fill_opacity',
            field=models.DecimalField(decimal_places=2, default=0.6, help_text='От 0.0 (прозрачно) до 1.0 (непрозрачно)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Прозрачность заливки'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='polygon_stroke_color',
            field=models.CharField(default='#ffd21e', help_text='Цвет в формате #RRGGBB (например: #ffd21e)', max_length=7, verbose_name='Цвет обводки полигона'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='polygon_stroke_opacity',
            field=models.DecimalField(decimal_places=2, default=0.9, help_text='От 0.0 (прозрачно) до 1.0 (непрозрачно)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Прозрачность обводки'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='polygon_stroke_width',
            field=models.PositiveIntegerField(default=5, help_text='Ширина линии в пикселях', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Ширина обводки'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Необязательно, если задан полигон', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта центра'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Необязательно, если задан полигон', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота центра'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Необязательно, если задан полигон', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Радиус зоны (км)'),
        ),
    ]
