# Generated by Django 4.2.7 on 2025-08-30 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес самовывоза'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='pickup_available',
            field=models.BooleanField(default=True, verbose_name='Доступен самовывоз'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Координаты точки самовывоза', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта точки самовывоза'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Координаты точки самовывоза', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота точки самовывоза'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='pickup_time',
            field=models.CharField(default='15-20 минут', max_length=100, verbose_name='Время готовности для самовывоза'),
        ),
    ]
