# Generated by Django 4.2.7 on 2025-08-30 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_deliveryzone_pickup_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ресторана')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес ресторана')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('pickup_available', models.BooleanField(default=True, verbose_name='Доступен самовывоз')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная сумма заказа для самовывоза')),
                ('pickup_time', models.CharField(default='15-20 минут', max_length=100, verbose_name='Время готовности для самовывоза')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Часы работы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='deliveryzone',
            name='api_deliver_city_ec5d6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryzone',
            name='api_deliver_is_acti_8035b9_idx',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='pickup_available',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='pickup_longitude',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='updated_at',
        ),
    ]
