# Generated by Django 4.2.7 on 2025-08-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_discount_amount_order_final_price_promocode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='used_by',
        ),
    ]
