# Generated by Django 4.2.7 on 2025-08-31 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_promocode_used_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='used_at',
        ),
        migrations.AddField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='Сколько раз можно использовать промокод (0 = безлимит)', verbose_name='Максимальное количество использований'),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'ordering': ['-used_at'],
                'unique_together': {('promo_code', 'user')},
            },
        ),
    ]
