# Generated by Django 4.2.7 on 2025-09-01 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_alter_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время назначения оператору'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначенный оператор'),
        ),
        migrations.AddField(
            model_name='order',
            name='operator_call_result',
            field=models.CharField(blank=True, choices=[('confirmed', 'Подтвержден'), ('cancelled', 'Отменен'), ('modified', 'Изменен'), ('unreachable', 'Не дозвонился'), ('wrong_number', 'Неверный номер')], max_length=50, verbose_name='Результат звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='operator_call_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время звонка оператора'),
        ),
        migrations.AddField(
            model_name='order',
            name='operator_called',
            field=models.BooleanField(default=False, verbose_name='Оператор звонил'),
        ),
        migrations.AddField(
            model_name='order',
            name='operator_notes',
            field=models.TextField(blank=True, help_text='Внутренние заметки оператора', verbose_name='Заметки оператора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен оператору'), ('operator_processing', 'Обрабатывается оператором'), ('confirmed', 'Подтвержден клиентом'), ('preparing', 'Готовится'), ('ready_for_delivery', 'Готов к доставке'), ('delivering', 'Доставляется'), ('completed', 'Выполнен'), ('cancelled', 'Отменен'), ('rejected', 'Отклонен')], default='pending', max_length=20),
        ),
    ]
