# Generated by Django 4.2.7 on 2025-09-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_order_assigned_at_order_assigned_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operator_order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер заказа оператора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('new', 'Новый'), ('assigned', 'Назначен оператору'), ('operator_processing', 'Обрабатывается оператором'), ('confirmed', 'Подтвержден клиентом'), ('preparing', 'Готовится'), ('ready_for_delivery', 'Готов к доставке'), ('delivering', 'Доставляется'), ('completed', 'Выполнен'), ('cancelled', 'Отменен'), ('rejected', 'Отклонен')], default='pending', max_length=20),
        ),
    ]
