# Generated by Django 4.2.7 on 2025-09-04 08:28

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('phone', models.CharField(max_length=20, validators=[api.models.validate_uzbek_phone_number], verbose_name='Телефон')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('busy', 'Занят'), ('offline', 'Не в сети'), ('blocked', 'Заблокирован')], default='offline', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('max_orders', models.PositiveIntegerField(default=3, verbose_name='Максимум заказов')),
                ('current_orders_count', models.PositiveIntegerField(default=0, verbose_name='Текущее количество заказов')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Всего доставок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_driver', to='api.user')),
            ],
            options={
                'verbose_name': 'Курьер доставки',
                'verbose_name_plural': 'Курьеры доставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Назначен'), ('accepted', 'Принят'), ('picked_up', 'Забран'), ('delivering', 'Доставляется'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='assigned', max_length=20, verbose_name='Статус')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата забора')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.deliverydriver', verbose_name='Курьер')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to='api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Назначение доставки',
                'verbose_name_plural': 'Назначения доставки',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverydriver',
            index=models.Index(fields=['status'], name='api_deliver_status_758a53_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverydriver',
            index=models.Index(fields=['is_active'], name='api_deliver_is_acti_c7b344_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverydriver',
            index=models.Index(fields=['telegram_id'], name='api_deliver_telegra_ebb3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverydriver',
            index=models.Index(fields=['rating'], name='api_deliver_rating_c81d38_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['status'], name='api_deliver_status_58f850_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['driver'], name='api_deliver_driver__ede9d8_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['order'], name='api_deliver_order_i_27bc43_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['assigned_at'], name='api_deliver_assigne_4cf33e_idx'),
        ),
    ]
