# Generated by Django 4.2.7 on 2025-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_deliverydriver_deliveryassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydriver',
            name='restaurants',
            field=models.ManyToManyField(blank=True, help_text='Рестораны, с которыми работает курьер', to='api.restaurant', verbose_name='Рестораны'),
        ),
    ]
