# Generated by Django 4.2.7 on 2025-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_deliverydriver_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='telegram_group_id',
            field=models.CharField(blank=True, help_text='ID группы Telegram для уведомлений о заказах (например: -1001234567890)', max_length=50, null=True, verbose_name='ID Telegram группы ресторана'),
        ),
    ]
