# Generated by Django 4.2.7 on 2025-09-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_restaurant_telegram_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID сообщения в Telegram'),
        ),
    ]
