# Generated by Django 4.2.7 on 2025-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_telegram_message_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['name'], 'verbose_name': 'Дополнение', 'verbose_name_plural': 'Дополнения'},
        ),
        migrations.RemoveIndex(
            model_name='addon',
            name='api_addon_categor_8eac42_idx',
        ),
        migrations.RemoveIndex(
            model_name='addon',
            name='api_addon_categor_c2189f_idx',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='category',
        ),
        migrations.AlterField(
            model_name='addon',
            name='available_for_categories',
            field=models.ManyToManyField(blank=True, related_name='available_addons', to='api.category', verbose_name='Категории'),
        ),
    ]
