# Generated by Django 4.2.7 on 2025-09-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_addon_category_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('new', 'Новый'), ('assigned', 'Назначен оператору'), ('confirmed', 'Подтвержден клиентом'), ('preparing', 'Готовится'), ('ready_for_delivery', 'Готов к доставке'), ('delivering', 'Доставляется'), ('completed', 'Выполнен'), ('cancelled', 'Отменен'), ('rejected', 'Отклонен')], default='pending', max_length=20),
        ),
    ]
