# Generated by Django 4.2.7 on 2025-09-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_operator_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='receipt_photo',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Фото чека'),
        ),
    ]
