# Generated by Django 4.2.7 on 2025-09-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_make_address_optional_for_pickup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['priority'], name='api_categor_priorit_0dc0de_idx'),
        ),
    ]
