# Generated by Django 4.2.7 on 2025-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_priority_to_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available_from_time',
            field=models.TimeField(blank=True, help_text='Время начала доступности (например, 08:00)', null=True, verbose_name='Доступен с'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_to_time',
            field=models.TimeField(blank=True, help_text='Время окончания доступности (например, 22:00)', null=True, verbose_name='Доступен до'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='use_time_restriction',
            field=models.BooleanField(default=False, help_text='Если включено, товар будет скрыт вне указанного времени', verbose_name='Использовать ограничение по времени'),
        ),
    ]
