# Generated by Django 4.2.7 on 2025-09-03 12:51

import app_cashier.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0019_order_payment_method'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, help_text='Формат: +998 90 123 45 67 или 901234567', max_length=20, null=True, unique=True, validators=[app_cashier.models.validate_uzbek_phone_number], verbose_name='Номер телефона')),
                ('is_active_cashier', models.BooleanField(default=True, verbose_name='Активный кассир')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('processed_orders_count', models.PositiveIntegerField(default=0, verbose_name='Количество обработанных заказов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='cashier_set', related_query_name='cashier', to='auth.group', verbose_name='groups')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashiers', to='api.restaurant', verbose_name='Ресторан')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='cashier_set', related_query_name='cashier', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Кассир',
                'verbose_name_plural': 'Кассиры',
                'ordering': ['-processed_orders_count'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения заказа')),
                ('started_preparing_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала приготовления')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Время готовности')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('received', 'Получен'), ('preparing', 'Готовится'), ('ready', 'Готов'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='received', max_length=20, verbose_name='Статус обработки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки кассира')),
                ('estimated_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценочное время приготовления (минуты)')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_processings', to='app_cashier.cashier', verbose_name='Кассир')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_processing', to='api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Обработка заказа кассиром',
                'verbose_name_plural': 'Обработка заказов кассирами',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['cashier', 'status'], name='app_cashier_cashier_105a9a_idx'), models.Index(fields=['status'], name='app_cashier_status_074eda_idx'), models.Index(fields=['received_at'], name='app_cashier_receive_3830da_idx'), models.Index(fields=['order'], name='app_cashier_order_i_ef7b3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashierSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала смены')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания смены')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус сессии')),
                ('orders_processed', models.PositiveIntegerField(default=0, verbose_name='Количество обработанных заказов')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки о смене')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app_cashier.cashier', verbose_name='Кассир')),
            ],
            options={
                'verbose_name': 'Сессия кассира',
                'verbose_name_plural': 'Сессии кассиров',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['cashier', 'status'], name='app_cashier_cashier_b207f9_idx'), models.Index(fields=['start_time'], name='app_cashier_start_t_772b94_idx'), models.Index(fields=['status'], name='app_cashier_status_5003c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashierNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'Новый заказ'), ('order_status_change', 'Изменение статуса заказа'), ('system', 'Системное уведомление'), ('reminder', 'Напоминание')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app_cashier.cashier', verbose_name='Кассир')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashier_notifications', to='api.order', verbose_name='Связанный заказ')),
            ],
            options={
                'verbose_name': 'Уведомление кассира',
                'verbose_name_plural': 'Уведомления кассиров',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cashier', 'is_read'], name='app_cashier_cashier_4dfe40_idx'), models.Index(fields=['notification_type'], name='app_cashier_notific_9c1fef_idx'), models.Index(fields=['created_at'], name='app_cashier_created_178770_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashierAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Общее количество заказов')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='Завершенные заказы')),
                ('cancelled_orders', models.PositiveIntegerField(default=0, verbose_name='Отмененные заказы')),
                ('avg_preparation_time', models.PositiveIntegerField(default=0, verbose_name='Среднее время приготовления (минуты)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая выручка')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='app_cashier.cashier', verbose_name='Кассир')),
            ],
            options={
                'verbose_name': 'Аналитика кассира',
                'verbose_name_plural': 'Аналитика кассиров',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['cashier', 'date'], name='app_cashier_cashier_4b643f_idx'), models.Index(fields=['date'], name='app_cashier_date_eb0554_idx'), models.Index(fields=['avg_preparation_time'], name='app_cashier_avg_pre_de751f_idx')],
                'unique_together': {('cashier', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='cashier',
            index=models.Index(fields=['is_active_cashier'], name='app_cashier_is_acti_e837a8_idx'),
        ),
        migrations.AddIndex(
            model_name='cashier',
            index=models.Index(fields=['processed_orders_count'], name='app_cashier_process_e41871_idx'),
        ),
        migrations.AddIndex(
            model_name='cashier',
            index=models.Index(fields=['telegram_id'], name='app_cashier_telegra_dfa03d_idx'),
        ),
        migrations.AddIndex(
            model_name='cashier',
            index=models.Index(fields=['phone'], name='app_cashier_phone_1f71fa_idx'),
        ),
        migrations.AddIndex(
            model_name='cashier',
            index=models.Index(fields=['restaurant'], name='app_cashier_restaur_ae25de_idx'),
        ),
    ]
