# Generated by Django 4.2.7 on 2025-09-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cashier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='app_cashier.cashier', verbose_name='Кассир')),
            ],
            options={
                'verbose_name': 'Токен кассира',
                'verbose_name_plural': 'Токены кассиров',
            },
        ),
    ]
