# Generated by Django 4.2.7 on 2025-09-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cashier', '0002_cashiertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprocessing',
            name='status',
            field=models.CharField(choices=[('received', 'Получен'), ('preparing', 'Готовится'), ('ready', 'Готов'), ('delivering', 'Доставляется'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='received', max_length=20, verbose_name='Статус обработки'),
        ),
    ]
