# Generated by Django 4.2.7 on 2025-09-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cashier', '0003_alter_orderprocessing_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cashier',
            managers=[
            ],
        ),
    ]
