# Generated by Django 4.2.7 on 2025-07-26 01:58

import app_operator.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_alter_menuitem_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(help_text='Формат: +998 90 123 45 67 или 901234567', max_length=20, unique=True, validators=[app_operator.models.validate_uzbek_phone_number], verbose_name='Номер телефона')),
                ('is_active_operator', models.BooleanField(default=True, verbose_name='Активный оператор')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('completed_orders_count', models.PositiveIntegerField(default=0, verbose_name='Количество выполненных заказов')),
                ('avg_delivery_time', models.PositiveIntegerField(default=0, verbose_name='Среднее время доставки (минуты)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_zones', models.ManyToManyField(blank=True, related_name='operators', to='api.deliveryzone', verbose_name='Назначенные зоны доставки')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
                'ordering': ['-rating', '-completed_orders_count'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('reason', models.TextField(blank=True, verbose_name='Причина изменения')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса заказа',
                'verbose_name_plural': 'История статусов заказов',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['order', 'changed_at'], name='app_operato_order_i_503e33_idx'), models.Index(fields=['operator'], name='app_operato_operato_fa35af_idx'), models.Index(fields=['new_status'], name='app_operato_new_sta_02e619_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Время назначения')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время принятия')),
                ('status', models.CharField(choices=[('assigned', 'Назначен'), ('accepted', 'Принят'), ('rejected', 'Отклонен'), ('completed', 'Выполнен')], default='assigned', max_length=20, verbose_name='Статус назначения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки оператора')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Назначение заказа',
                'verbose_name_plural': 'Назначения заказов',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['operator', 'status'], name='app_operato_operato_143f6b_idx'), models.Index(fields=['status'], name='app_operato_status_656fe1_idx'), models.Index(fields=['assigned_at'], name='app_operato_assigne_d80e1f_idx'), models.Index(fields=['order'], name='app_operato_order_i_ca7fce_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperatorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала смены')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания смены')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус сессии')),
                ('orders_handled', models.PositiveIntegerField(default=0, verbose_name='Количество обработанных заказов')),
                ('total_delivery_time', models.PositiveIntegerField(default=0, verbose_name='Общее время доставки (минуты)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки о смене')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Сессия оператора',
                'verbose_name_plural': 'Сессии операторов',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['operator', 'status'], name='app_operato_operato_a47d10_idx'), models.Index(fields=['start_time'], name='app_operato_start_t_eec790_idx'), models.Index(fields=['status'], name='app_operato_status_a09148_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperatorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'Новый заказ'), ('order_status_change', 'Изменение статуса заказа'), ('system', 'Системное уведомление'), ('reminder', 'Напоминание')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_notifications', to='api.order', verbose_name='Связанный заказ')),
            ],
            options={
                'verbose_name': 'Уведомление оператора',
                'verbose_name_plural': 'Уведомления операторов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operator', 'is_read'], name='app_operato_operato_47f984_idx'), models.Index(fields=['notification_type'], name='app_operato_notific_ce5329_idx'), models.Index(fields=['created_at'], name='app_operato_created_edd1dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperatorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Общее количество заказов')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='Выполненные заказы')),
                ('cancelled_orders', models.PositiveIntegerField(default=0, verbose_name='Отмененные заказы')),
                ('total_delivery_time', models.PositiveIntegerField(default=0, verbose_name='Общее время доставки (минуты)')),
                ('avg_delivery_time', models.PositiveIntegerField(default=0, verbose_name='Среднее время доставки (минуты)')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий заработок')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Аналитика оператора',
                'verbose_name_plural': 'Аналитика операторов',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['operator', 'date'], name='app_operato_operato_c3667b_idx'), models.Index(fields=['date'], name='app_operato_date_462459_idx'), models.Index(fields=['avg_delivery_time'], name='app_operato_avg_del_dd5131_idx')],
                'unique_together': {('operator', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['is_active_operator'], name='app_operato_is_acti_804656_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['rating'], name='app_operato_rating_515783_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['completed_orders_count'], name='app_operato_complet_32d2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['telegram_id'], name='app_operato_telegra_c1908c_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['phone'], name='app_operato_phone_615180_idx'),
        ),
    ]
