# Generated by Django 4.2.7 on 2025-08-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['-completed_orders_count'], 'verbose_name': 'Оператор', 'verbose_name_plural': 'Операторы'},
        ),
        migrations.RemoveIndex(
            model_name='operator',
            name='app_operato_rating_515783_idx',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='avg_delivery_time',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='operatorsession',
            name='total_delivery_time',
        ),
    ]
