# Generated by Django 4.2.7 on 2025-08-07 12:30

from django.db import migrations, models
import app_operator.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0002_alter_operator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='phone',
            field=models.CharField(
                blank=True,
                help_text='Формат: +998 90 123 45 67 или 901234567',
                max_length=20,
                null=True,
                unique=True,
                validators=[app_operator.models.validate_uzbek_phone_number],
                verbose_name='Номер телефона'
            ),
        ),
    ] 