# Generated by Django 4.2.7 on 2025-09-02 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0003_alter_operator_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorOrderNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Последний номер заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_numbers', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Номер заказа оператора',
                'verbose_name_plural': 'Номера заказов операторов',
                'indexes': [models.Index(fields=['operator', 'date'], name='app_operato_operato_d0643f_idx')],
                'unique_together': {('operator', 'date')},
            },
        ),
    ]
