# Generated by Django 4.2.7 on 2025-09-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_operator', '0004_operatorordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='operator_set', related_query_name='operator', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='operator_set', related_query_name='operator', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
