# Generated by Django 4.2.7 on 2025-09-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0006_operatortoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatorToken',
        ),
    ]
